config/routes.rb
Rails.application.routes.draw do

    devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'auth/:provider/callback', to: 'sessions#create'

  post 'addFriend', to: "users#addFriend"
  get 'search', to: "users#index_friends"
  get 'acceptFriend/:id', to: "users#accept_friends"
  get 'declineFriend/:id', to: "users#decline_friends"
  get 'removeFriend/:id', to: "users#remove_friends"


  resources :notifications
  # resources :orders

  resources :users do
  resources :orders
	resources :gruops do
		resources :members
        end
  end
  resources :ordermembers
  root to: 'orders#index'

  get '/invitedfriend/:id', to: 'orders#invitedfriends', as: 'invitedfriends'
  get '/joinedfriend/:id', to: 'orders#joinedfriends', as: 'joinedfriends'

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ordermember.rb
class Ordermember < ApplicationRecord
  belongs_to :user
  belongs_to :order
  # after_create_commit { notify }

  # private
  #
  # def notify
  #   if self.status=="invited"
  #     Notification.create(event: "#{self.order.user.name} #{self.status} you to his order", user: self.user, order: self.order)
  #   end
  #
  # end
end

app/controllers/ordermembers_controller.rb
class OrdermembersController < ApplicationController
  before_action :set_ordermember, only: [ :show, :edit, :update, :destroy]
  before_action :set_notifications
  # GET /ordermembers
  # GET /ordermembers.json
  def index
    @notifications = Notification.all.reverse
    @ordermembers = Ordermember.all
  end

  # GET /ordermembers/1
  # GET /ordermembers/1.json
  def show

  end

  # GET /ordermembers/new
  def new
    # byebug
    @users = params[:usersToSend]

    @user = User.find params[:user_id]
    @order = Order.find params[:order_id]
    @ordermember = @order.ordermembers.new
  end

  # GET /ordermembers/1/edit
  def edit
    @ordermember.status="joined"
  end

  # POST /ordermembers
  # POST /ordermembers.json
  def create
    # @user=current_user
    # @order=Order.find(params[:order_id])
    @ordermember = Ordermember.new(ordermember_params)

    @order=@ordermember.order
    @ordermembers=@order.ordermembers
    @duplicatedMember = @ordermembers.select{ |ordermember| ordermember.status == "joined" && ordermember.user.id==@ordermember.user.id && ordermember.order.id==@ordermember.order.id}
    # @ordermember.user_id = @user.id
    if @duplicatedMember
      @ordermember.status="duplicated"
    else
      @ordermember.status="joined"
    end

    respond_to do |format|
      if @ordermember.save
        format.html { redirect_to user_order_path(@ordermember.order.user,@ordermember.order), notice: 'Ordermember was successfully created.' }
        format.json { render :show, status: :created, location: @ordermember }
      else
        format.html { render :new }
        format.json { render json: @ordermember.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordermembers/1
  # PATCH/PUT /ordermembers/1.json
  def update

    respond_to do |format|
      if @ordermember.update(ordermember_params)
        format.html { redirect_to @ordermember, notice: 'Ordermember was successfully updated.' }
        format.json { render :show, status: :ok, location: @ordermember }
      else
        format.html { render :edit }
        format.json { render json: @ordermember.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordermembers/1
  # DELETE /ordermembers/1.json
  def destroy
    @ordermember.destroy
    respond_to do |format|
      format.html { redirect_to ordermembers_url, notice: 'Ordermember was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordermember
      @ordermember = Ordermember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ordermember_params
      params.require(:ordermember).permit(:user_id, :order_id, :status, :item, :amount, :price, :comment)
    end
    def set_notifications
      @user=current_user
      @notifications = @user.notifications.all.reverse
    end
end

app/helpers/ordermembers_helper.rb
module OrdermembersHelper
end

app/views/ordermembers/_form.html.erb
<%= form_for([@user,@order,@ordermember]) do |f| %>
  <% if ordermember.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ordermember.errors.count, "error") %> prohibited this ordermember from being saved:</h2>

      <ul>
      <% ordermember.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :order_id %>
    <%= f.text_field :order_id %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :item %>
    <%= f.text_field :item %>
  </div>
  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ordermembers/edit.html.erb
<h1>Editing Ordermember</h1>

<%= render 'form', ordermember: @ordermember %>

<%= link_to 'Show', @ordermember %> |
<%= link_to 'Back', ordermembers_path %>

app/views/ordermembers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ordermembers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Order</th>
      <th>Status</th>
      <th>Item</th>
      <th>Amount</th>
      <th>Price</th>
      <th>Comment</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordermembers.each do |ordermember| %>
      <tr>
        <td><%= ordermember.user.name %></td>
        <td><%= ordermember.order.id %></td>
        <td><%= ordermember.status %></td>
        <td><%= ordermember.item %></td>
        <td><%= ordermember.amount %></td>
        <td><%= ordermember.price %></td>
        <td><%= ordermember.comment %></td>
        <td><%= link_to 'Show', ordermember_path(ordermember) %></td>
        <td><%= link_to 'Edit', edit_ordermember_path(ordermember) %></td>
        <td><%= link_to 'Destroy', ordermember_path(ordermember), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ordermember', new_ordermember_path %>

app/views/ordermembers/new.html.erb
<h1>New Ordermember</h1>

<%= render 'form', ordermember: @ordermember %>

<%= link_to 'Back', user_order_ordermembers_path %>

app/views/ordermembers/show.html.erb
<h1>Ordermembers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Image</th>
    </tr>
  </thead>

  <tbody>
    <% @ordermembers.each do |ordermember| %>
      <tr>
        <td><%= ordermember.user.name %></td>
        <td><%= ordermember.user.avatar %></td>
        
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', ordermembers_path %>