config/routes.rb
Rails.application.routes.draw do

    devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'auth/:provider/callback', to: 'sessions#create'

  post 'addFriend', to: "users#addFriend"
  get 'search', to: "users#index_friends"
  get 'acceptFriend/:id', to: "users#accept_friends"
  get 'declineFriend/:id', to: "users#decline_friends"
  get 'removeFriend/:id', to: "users#remove_friends"


  resources :notifications
  # resources :orders

  resources :users do
  resources :orders
	resources :gruops do
		resources :members
        end
  end
  resources :ordermembers
  root to: 'orders#index'

  get '/invitedfriend/:id', to: 'orders#invitedfriends', as: 'invitedfriends'
  get '/joinedfriend/:id', to: 'orders#joinedfriends', as: 'joinedfriends'

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :ordermembers
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  def user_name
  user.try(:name)
end

def user_name=(name)
  self.user = User.find_by(name: name) if name.present?
end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy, :invitedfriends, :joinedfriends]
  before_action :set_notifications
  # GET /orders
  # GET /orders.json
  def index


    # byebug
    # @userOfOrder = User.find params[:user_id]
    @orders = @user.orders

  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @user = current_user
    @ordermember = Ordermember.new
    @ordermember.order = @order
    @ordermember.user=@user
    @currentOrderMembers = @order.ordermembers
    @invitedMembers = @currentOrderMembers.select{ |ordermember| ordermember.status == "invited"}
    @joinedMembers = @currentOrderMembers.select{ |ordermember| ordermember.status == "joined"}

  end

  # GET /orders/new
  def new
    # @notifications = Notification.all.reverse
    @user = current_user
    @order = @user.orders.new
  end

  # GET /orders/1/edit
  def edit
    @user = current_user
    # byebug

    finishOrder={ name: @order.name, restaurant: @order.restaurant, status: "finished", avatar: @order.avatar}
    @order.update(finishOrder)
    redirect_to user_orders_path(@user)
  end

  # POST /orders
  # POST /orders.json
  def create
    # puts(order_params)
    # byebug
    @user = current_user
    @order = @user.orders.new(order_params)
    if params[:users_to_send]
      usersInvited = params[:users_to_send].split(",")
      usersInvited.push(@user.name)
    end
    @order.status="waiting"
    # byebug

    respond_to do |format|
      if @order.save
        if params[:users_to_send]
          for oneUser in usersInvited
            @user=User.find_by_name(oneUser)
            newOrderMember={ order_id: @order.id, user_id: @user.id, status: "invited"}
            # puts(newOrderMember)
            @order.ordermembers.create(newOrderMember)
            Notification.create(event: "#{@order.user.name} invited you to his order", user: @user, order: @order)
            # byebug
          end
        end

        format.html { redirect_to user_order_path(@order.user,@order), notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to user_order_path(@order.user,@order), notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    # @user = current_user
    # @order.destroy
    # respond_to do |format|
    #   format.html { redirect_to user_orders_path(@order), notice: 'Order was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
    @user = current_user
    # byebug

    finishOrder={ name: @order.name, restaurant: @order.restaurant, status: "cancelled", avatar: @order.avatar}
    @order.update(finishOrder)
    redirect_to user_orders_path(@user)
  end
  def invitedfriends
      @currentOrderMembers = @order.ordermembers
      @ordermembers = @currentOrderMembers.select{ |ordermember| ordermember.status == "invited"}
  end
  def joinedfriends
      @currentOrderMembers = @order.ordermembers
      @ordermembers = @currentOrderMembers.select{ |ordermember| ordermember.status == "joined"}
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @notifications = Notification.all.reverse
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:name, :restaurant, :status, :avatar)
    end
    def set_notifications
      @user=current_user
      @notifications = @user.notifications.all.reverse
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for [@user,@order] do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "For" %>
    <select name="order[name]" id="order_name">
      <option value="breakfast">BreakFast</option>
      <option value="lunch">Lunch</option>

      <option value="dinner">Dinner</option>
    </select>

  </div>

  <div class="field">
    <%= f.label :restaurant %>
    <%= f.text_field :restaurant %>
  </div>


  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_name , data: { autocomplete_source: users_path} %>
  </div>
  <div class="field">
    <ul id="added">

    </ul>

</div>
<div class="field">
  <%= f.file_field :avatar %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', user_order_path(@order.user,@order.id) %> |
<%= link_to 'Back', user_orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>

      <th>Order</th>
      <th>Restaurant</th>
      <th>Status</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
    <% if order.status != "cancelled" %>
      <tr>
        
        <td><%= order.name %></td>
        <td><%= order.restaurant %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'View', user_order_path(order.user,order.id) %></td>
        <% if order.status != "finished" %>


        <td><%= link_to 'finish', edit_user_order_path(order.user,order.id) %></td>
        <td><%= link_to 'Cancel', user_order_path(order.user,order.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_user_order_path(@user) %>

app/views/orders/invitedfriends.html.erb
<h1>invitedfriends</h1>


<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Avatar</th>

    </tr>
  </thead>

  <tbody>
    <% @ordermembers.each do |ordermember| %>
      <tr>
        <td><%= ordermember.user.name %></td>
        <td><%= image_tag ordermember.user.avatar.url(:medium) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', user_order_path(@order.user,@order) %>

app/views/orders/joinedfriends.html.erb
<h1>joinedfriends</h1>


<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Avatar</th>

    </tr>
  </thead>

  <tbody>
    <% @ordermembers.each do |ordermember| %>
      <tr>
        <td><%= ordermember.user.name %></td>
        <td><%= image_tag ordermember.user.avatar.url(:medium) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', user_order_path(@order.user,@order) %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', user_orders_path() %>

app/views/orders/show.html.erb
<h1>Order details</h1>
<table>
  <thead>
    <tr>
      <th>Person</th>
      <th>Item</th>
      <th>amount</th>
      <th>price</th>
      <th>comment</th>
      <th>status</th>

    </tr>
  </thead>
<% @order.ordermembers.each do |ordermember| %>
<% if ordermember.status == "joined" || ordermember.status == "duplicated" %>



  <tbody>

      <tr>
        <td><%= ordermember.user.name %></td>
        <td><%= ordermember.item %></td>
        <td><%= ordermember.amount %></td>
        <td><%= ordermember.price %></td>
        <td><%= ordermember.comment %></td>
        <td><%= ordermember.status %></td>
      </tr>
      <% end %>
      <% end %>
  </tbody>
</table>



<% if @order.status=="waiting" %>



<h2>Add item:</h2>
<%= form_for(@ordermember) do |f| %>
<div class="field">

  <%= f.hidden_field :user_id %>
</div>

<div class="field">
  <%= f.hidden_field :order_id %>
</div>

<div class="field">
  <%= f.hidden_field :status %>
</div>
<div class="field">
  <%= f.label :item %>
  <%= f.text_field :item %>
</div>
<div class="field">
  <%= f.label :amount %>
  <%= f.text_field :amount %>
</div>
<div class="field">
  <%= f.label :price %>
  <%= f.text_field :price %>
</div>
<div class="field">
  <%= f.label :comment %>
  <%= f.text_field :comment %>
</div>

<div class="actions">
  <%= f.submit "add"%>
</div>
<% end %>
<% end %>

<%= link_to "#{@invitedMembers.length} friends invited, click to view", invitedfriends_path(@order) %>
<br>
<%= link_to "#{@joinedMembers.length} friends joined, click to view", joinedfriends_path(@order) %>