config/routes.rb
Rails.application.routes.draw do

    devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  get 'auth/:provider/callback', to: 'sessions#create'

  post 'addFriend', to: "users#addFriend"
  get 'search', to: "users#index_friends"
  get 'acceptFriend/:id', to: "users#accept_friends"
  get 'declineFriend/:id', to: "users#decline_friends"
  get 'removeFriend/:id', to: "users#remove_friends"


  resources :notifications
  # resources :orders

  resources :users do
  resources :orders
	resources :gruops do
		resources :members
        end
  end
  resources :ordermembers
  root to: 'orders#index'

  get '/invitedfriend/:id', to: 'orders#invitedfriends', as: 'invitedfriends'
  get '/joinedfriend/:id', to: 'orders#joinedfriends', as: 'joinedfriends'

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gruop.rb
class Gruop < ApplicationRecord
  belongs_to :user
  has_many :users
  has_many :members
end

app/controllers/gruops_controller.rb
class GruopsController < ApplicationController
  before_action :set_gruop, only: [:show, :edit, :update, :destroy]
  before_action :set_notifications
  # GET /gruops
  # GET /gruops.json
  def index
    @notifications = @user.notifications.reverse
    @user = User.find params[:user_id]
    @gruops = @user.gruops.all
  end

  # GET /gruops/1
  # GET /gruops/1.json
  def show
    @notifications = @user.notifications.reverse
   @users = User.all
  end

  # GET /gruops/new
  def new
    @notifications = @user.notifications.reverse
    @user = User.find params[:user_id]
    @gruop = @user.gruops.new
  end

  # GET /gruops/1/edit
  def edit
    @notifications = @user.notifications.reverse
  end

  # POST /gruops
  # POST /gruops.json
  def create
    @notifications = @user.notifications.reverse
    @user = User.find params[:user_id]
    @gruop = @user.gruops.new(gruop_params)

    respond_to do |format|

      if @gruop.save
         @member = @gruop.members.new(user_id: @user.id)
         @member.save
        format.html { redirect_to [@user,@gruop], notice: 'Gruop was successfully created.' }
        format.json { render :show, status: :created, location: @gruop }
      else
        format.html { render :new }
        format.json { render json: @gruop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gruops/1
  # PATCH/PUT /gruops/1.json
  def update
    respond_to do |format|
      if @gruop.update(gruop_params)
        format.html { redirect_to [@user,@gruop], notice: 'Gruop was successfully updated.' }
        format.json { render :show, status: :ok, location: @gruop }
      else
        format.html { render :edit }
        format.json { render json: @gruop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gruops/1
  # DELETE /gruops/1.json
  def destroy
    @gruop.destroy
    respond_to do |format|
      format.html { redirect_to gruops_url, notice: 'Gruop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gruop
      @user = User.find(params[:user_id])
      @gruop = @user.gruops.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gruop_params
      params.require(:gruop).permit(:name, :user_id)
    end
    def set_notifications
      @user=current_user
      @notifications = @user.notifications.all.reverse
    end
end

app/helpers/gruops_helper.rb
module GruopsHelper
end

app/views/gruops/_form.html.erb
<%= form_for([@user,gruop]) do |f| %>
  <% if gruop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gruop.errors.count, "error") %> prohibited this gruop from being saved:</h2>

      <ul>
      <% gruop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gruops/edit.html.erb
<h1>Editing Gruop</h1>

<%= render 'form', gruop: @gruop %>

<%= link_to 'Show', user_gruop_path %> |
<%= link_to 'Back', user_gruops_path %>

app/views/gruops/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gruops</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gruops.each do |gruop| %>
      <tr>
        <td><%= gruop.id %></td>
        <td><%= gruop.name %></td>
        <td><%= gruop.user %></td>
        <%if(@user==current_user)%>
        <td><%= link_to 'Show', user_gruop_path(gruop.user,gruop) %></td>
        <td><%= link_to 'Edit', edit_user_gruop_path(@user,gruop) %></td>
        <td><%= link_to 'Destroy', [@user,gruop], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gruop', new_user_gruop_path %>

app/views/gruops/new.html.erb
<h1>New Gruop</h1>

<%= render 'form', gruop: @gruop %>

<%= link_to 'Back', user_gruops_path %>

app/views/gruops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gruop.name %>
</p>

<p style="display: none">
  <strong>User:</strong>
  <%= @gruop.user %>
</p>

<%= link_to 'Edit', user_gruop_path(@user,@gruop) %> |
<%= link_to 'Back', user_gruops_path %>

<h1>Members inside this Group</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>

<% @gruop.members.each do |member| %>
      <tr>
	<td><%= member.id %></td>
        <td><%= member.user.name %></td>
	<td><%= member.user.email %></td>
  <td><%= link_to 'Remove from group', user_gruop_member_path(member.user,@gruop,member) , method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %></td>
      </tr>
    <% end %>

</tbody>
</table>
<h1>Members outside this Group</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
<% @users.each do |user| %>
  <% if @gruop.members %>
      <% @gruop.members.each do  |member| %>
      <% if member.user_id != user.id %>
            <tr>
      	<td><%= user.id %></td>
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <!-- <td><%= link_to 'Add Member', new_user_gruop_member_path(user,@gruop,@member),class:"btn btn-success" %></td> -->
      <!--  ========================================================== -->

      <%= form_for([@user,@gruop,Member.new], :method => :post, :class => "linkForm") do |f| %>
            <%= f.hidden_field :user_id, :value => "#{user.id}" %>
            <%= f.hidden_field :group_id, :value =>"#{member.gruop_id}" %>
            <td><%= f.submit 'add to group',class:"btn btn-success" %></td>
          <% end %>
      <!--  ========================================================== -->
            </tr>
           <%break%>
          <% end %>
        <% end %>
<%end%>
<% end %>
  </tbody>
</table>

<!--
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
	<td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user, class:"btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_user_path(user),class:"btn btn-warning" %></td>
	<td><%= link_to 'Add Member', new_user_gruop_member_path(user,@gruop,@member),class:"btn btn-success" %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' },class:"btn btn-danger" %></td>
      </tr>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %> -->